trigger:
- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'Kayal'
    cliInstallationRepo: 'jfrog-cli'
    installCustomVersion: true
    cliVersion: '1.46.0'
- task: ArtifactoryGenericDownload@3
  inputs:
    connection: 'Kayal'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "warnenduk-docker-local/*",
            "target": "dependencies/files/"
          }
        ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    dryRun: true
    failNoOp: false
    insecureTls: true
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: swarnenduk-docker-local.jfrog.io/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'Kayal'
    targetRepo: 'docker-local'
    imageName: 'swarnenduk-docker-local.jfrog.io/$(imageName):$(Build.BuildId)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: Kayal
    buildName: $(Build.DefinitionName)
    buildNumber: $(Build.BuildNumber)
- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'Kayal'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: false